### ISSUE TITLE
What’s your favorite museum?

### ISSUE THREAD

**Issue by lachlanjc** [jem-computer/ama#10]

**Comment by jem-computer** [comment]
I'm not sure if it's technically a museum, but I've seen a tonnnn of good exhibitions at [the Barbican](https://www.barbican.org.uk/) in London (and it's part of the [Barbican Estate](https://en.wikipedia.org/wiki/Barbican_Estate), which is one of my favorite places in London architecturally).

In the US, I loved the [Getty](https://en.wikipedia.org/wiki/J._Paul_Getty_Museum) in LA architecturally, but I thought the contents was kinda uninspiring.
