### ISSUE TITLE
What are you working on?

### ISSUE THREAD

**Issue by lachlanjc** [jem-computer/ama#2]

**Comment by jem-computer** [comment]
Currently, as of 4/26/17:
- [a react renderer for sketch](https://github.com/airbnb/react-sketchapp)
- an ecosystem of design ops tools around it
- [a monadic interface for style composition](https://github.com/jongold/further)
- VR design tools 👁 
- AI-assisted design tools 👁

**Comment by lachlanjc** [comment]
5 months later…😀

**Comment by jem-computer** [comment]
Mostly AI-assisted design tools :P - I don't have anything quite ready to demo quite yet, but soon :)

The tooling around react-sketchapp mostly turned into Component Picker - a Sketch plugin that lets you use Airbnb's react-primitives components in Sketch :) 
![image](https://user-images.githubusercontent.com/591643/30823673-dfa42ee0-a1e1-11e7-9c0b-197bab6ee80e.png)

![image](https://user-images.githubusercontent.com/591643/30823708-fdf3939a-a1e1-11e7-9654-ad002397cef2.png)

**Comment by lachlanjc** [comment]
@jongold 👀😮😍✨
