### ISSUE TITLE
autoplaying videos on paiting with code

### ISSUE THREAD

**Issue by TBD** [jem-computer/ama#4]
is there a reason for autoplaying the videos on paiting with code article ? my laptop fans went nuts and the browser tab was not even in focus 😞

**Comment by jem-computer** [comment]
Videos are wayyyyy smaller than GIFs, and they're pretty tiny so I figured it was weird if you had to click play - maybe I should switch them out though :(

**Comment by TBD** [comment]
maybe use https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API and check if video player is in view

**Comment by jem-computer** [comment]
whoa, this is awesome - hadn't seen it. I don't control our blog template, will pass it on though!
